services:
  mysql:
    build: 
      context: .
      dockerfile: Dockerfile_mysql
    volumes:
      - "db:/var/lib/mysql"
    expose:
      - 3306
    
  web:
    build:
      context: .
    volumes:
      - ./:/usr/src/crud
      - ${HOME}/.m2:/root/.m2
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    command: bash -c 'mvn package && mvn spring-boot:run'

volumes:
  db:
